### ISSUE TITLE
Awesome program!

### ISSUE THREAD

**Issue by plotting** [1Paint/GroupMe-Chat-History#1]
I get a "RuntimeError: maximum recursion depth exceeded in cmp" after 97818 lines of chat, wonder if there is a way to fix this? I'm just missing about 6 months of data

**Comment by 1Paint** [comment]
Hey, thanks for bringing this issue up. 
I changed the application to retrieve messages iteratively instead of recursively so the problem should be fixed. Let me know if it works.

**Comment by plotting** [comment]
That fixed it thank you!
