### ISSUE TITLE
Invalid Chat ID for an existing Chat

### ISSUE THREAD

**Issue by 1Paint** [1Paint/GroupMe-Chat-History#4]
cdonohue413:

> Hi there- how come everytime I get to the point where i put in my access token, it starts to load then before it starts retreiving, it says "The Chat ID Entered is Invalid, or there any no messages in the Chat". I know it's not empty, what is the issue? Any ideas? Thanks!

**Comment by 1Paint** [comment]
Hey cdonohue413. I'm assuming you're using 'get_chat_history_console_v1.0.py'.

Make sure you enter the chat ID without any spaces.
Make sure the chat ID corresponds to the chat type you entered previously, either 'group' or 'direct'. Let me know if you still have problems.

**Comment by rlhughes** [comment]
Hi 1Paint-I'm having this same issue. I enter in the correct chat type: 'group' and the ID with no spaces. Is there something else I might be doing wrong?

**Comment by 1Paint** [comment]
Hey hughes. It was a bug that arose from me being a bit careless in the code. It should be fixed now. Thanks for helping with the issue.
